# Generated by Django 4.2.2 on 2026-08-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_balance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='timelapse',
            constraint=models.UniqueConstraint(fields=('date', 'time_lapse', 'table_number'), name='unique_booking_slot'),
        ),
    ]
